catalog:
  '@astrojs/starlight': ^0.36.2
  '@chromatic-com/storybook': ^4.1.2
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@cucumber/cucumber': ^12.2.0
  '@cucumber/messages': ^30.1.0
  '@playwright/test': ^1.56.1
  '@secretlint/secretlint-rule-preset-recommend': ^11.2.5
  '@stryker-mutator/core': ^9.3.0
  '@stryker-mutator/typescript-checker': ^9.3.0
  '@stryker-mutator/vitest-runner': ^9.3.0
  '@supabase/supabase-js': ^2.78.0
  '@tailwindcss/postcss': ^4.1.16
  '@types/node': ^24.10.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitest/coverage-v8': ^4.0.6
  astro: ^5.15.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.39.0
  eslint-config-next: ^16.0.1
  lucide-react: ^0.552.0
  msw: ^2.11.6
  next: ^16.0.1
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.7.1
  react: ^19.2.0
  react-dom: ^19.2.0
  remark: ^15.0.1
  remark-cli: ^12.0.1
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.1
  remark-lint: ^10.0.1
  remark-preset-lint-consistent: ^6.0.1
  remark-preset-lint-recommended: ^7.0.1
  remark-toc: ^9.0.0
  secretlint: ^11.2.5
  storybook: ^10.0.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.16
  textlint: ^15.2.3
  textlint-filter-rule-allowlist: ^4.0.0
  textlint-filter-rule-comments: ^1.2.2
  textlint-plugin-html: ^1.0.1
  textlint-rule-preset-ja-technical-writing: ^12.0.2
  tw-animate-css: ^1.4.0
  typedoc: ^0.28.14
  typescript: ^5.9.3
  vitest: ^4.0.6
  zustand: ^5.0.8

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
