catalog:
  '@astrojs/starlight': 0.36.2
  '@chromatic-com/storybook': 4.1.2
  '@commitlint/cli': 20.1.0
  '@commitlint/config-conventional': 20.0.0
  '@cucumber/cucumber': 12.2.0
  '@cucumber/messages': 30.1.0
  '@eslint/css': 0.9.0
  '@eslint/js': 9.39.1
  '@playwright/test': 1.56.1
  '@poupe/eslint-plugin-tailwindcss': 0.2.4
  '@secretlint/secretlint-rule-preset-recommend': 11.2.5
  '@storybook/addon-a11y': 10.0.6
  '@storybook/addon-docs': 10.0.6
  '@storybook/addon-onboarding': 10.0.6
  '@storybook/addon-vitest': 10.0.6
  '@storybook/nextjs': 10.0.6
  '@stryker-mutator/core': 9.3.0
  '@stryker-mutator/typescript-checker': 9.3.0
  '@stryker-mutator/vitest-runner': 9.3.0
  '@supabase/ssr': ^0.7.0
  '@supabase/supabase-js': 2.80.0
  '@tailwindcss/postcss': 4.1.17
  '@tanstack/react-query': 5.90.7
  '@testing-library/dom': 10.4.1
  '@testing-library/react': 16.3.0
  '@textlint-ja/textlint-rule-preset-ai-writing': 1.6.1
  '@textlint/textlint-plugin-markdown': 15.2.3
  '@trivago/prettier-plugin-sort-imports': 6.0.0
  '@types/node': 24.10.0
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@vercel/analytics': 1.5.0
  '@vercel/speed-insights': 1.2.0
  '@vitest/coverage-v8': 4.0.8
  astro: 5.15.6
  chromatic: 13.3.3
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dependency-cruiser: 17.2.0
  eslint: 9.39.1
  eslint-config-next: 16.0.1
  eslint-config-prettier: 10.1.8
  eslint-plugin-boundaries: 5.1.0
  eslint-plugin-eslint-comments: 3.2.0
  eslint-plugin-functional: 9.0.2
  eslint-plugin-import: 2.32.0
  eslint-plugin-jsdoc: 61.1.12
  eslint-plugin-n: 17.23.1
  eslint-plugin-promise: 7.2.1
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.4.24
  eslint-plugin-regexp: 2.10.0
  eslint-plugin-security: 3.0.1
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-sonarjs: 3.0.5
  eslint-plugin-storybook: 10.0.6
  eslint-plugin-strict-dependencies: 1.3.27
  eslint-plugin-unicorn: 62.0.0
  eslint-plugin-unused-imports: 4.3.0
  jsdom: 27.1.0
  lefthook: 2.0.2
  lru-cache: 11.2.2
  lucide-react: 0.553.0
  msw: 2.12.1
  next: 16.0.1
  prettier: 3.6.2
  prettier-plugin-packagejson: 2.5.19
  prettier-plugin-tailwindcss: 0.7.1
  react: 19.2.0
  react-dom: 19.2.0
  remark: 15.0.1
  remark-cli: 12.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.1
  remark-lint: 10.0.1
  remark-preset-lint-consistent: 6.0.1
  remark-preset-lint-recommended: 7.0.1
  remark-toc: 9.0.0
  secretlint: 11.2.5
  storybook: 10.0.6
  stylelint: 16.25.0
  stylelint-config-standard: 39.0.1
  stylelint-config-tailwindcss: 1.0.0
  stylelint-declaration-strict-value: 1.10.11
  stylelint-high-performance-animation: 1.11.0
  stylelint-no-unsupported-browser-features: 8.0.5
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  textlint: 15.2.3
  textlint-filter-rule-allowlist: 4.0.0
  textlint-filter-rule-comments: 1.2.2
  textlint-plugin-html: 1.0.1
  textlint-rule-preset-ja-technical-writing: 12.0.2
  tw-animate-css: 1.4.0
  typedoc: 0.28.14
  typedoc-plugin-merge-modules: 7.0.0
  typedoc-theme-hierarchy: 6.0.0
  typescript: 5.9.3
  typescript-eslint: 8.46.3
  vitest: 4.0.8
  zod: 4.1.12
  zustand: 5.0.8

catalogMode: strict

cleanupUnusedCatalogs: true

disallowWorkspaceCycles: true

engineStrict: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@poupe/eslint-plugin-tailwindcss'
  - '@vercel/speed-insights'
  - core-js-pure
  - esbuild
  - lefthook
  - msw
  - sharp
  - unrs-resolver

preferWorkspacePackages: true

saveWorkspaceProtocol: true

shamefullyHoist: false

sharedWorkspaceLockfile: true

strictPeerDependencies: true
